# Un primer workflow to play around with the editor
 name: My First Workflow
 on:
   push:
     branches:
       - main
 jobs:
   first_job:
     name: My first job
     runs-on: ubuntu-latest    
     steps:
       - name: Greet the user
         run: |
           echo "Current branch is ${{ github.ref }}."
           echo "Hello world from ${{ github.actor}}. "
           
       - name: Checkout
         uses: actions/checkout@v4.1.0
         
       - name: Un listado del directorio
         run: tree

   Test:
     runs-on: ubuntu-latest
     environment: Test
     needs: first_job
     steps:
       - name: Greet the test user
         run: |
           echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}." 
           sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
           echo "My secret is '$sec'."
           
   Load-Test:
     runs-on: ubuntu-latest
     environment: Load_Test
     needs: first_job
     steps:
       - name: Greet the test user
         run: |
           echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
           sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
           echo "My secret is '$sec'."

   Production:
     runs-on: ubuntu-latest
     environment:
       name: Production
       url: https://writeabout.net
     needs: [Test, Load-Test]
     steps:
       - name: Greet the test user
         run: |
           echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
           sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
           echo "My secret is '$sec'."
    
